<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Kab_model2 extends CI_Model
{

    public $table = 'ssgi2022_dict2';
    public $id = 'caseids';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
        $this->db= $this->load->database("db2", TRUE);
    }

    // datatables
    function json($data) {
        //$this->datatables2->select("concat('KECAMATAN ',json_unquote(json_extract(uncompress(questionnaire), '$.BLOK_13.KEC_TEXT')))as kec,caseids,json_extract(uncompress(questionnaire), '$.id.P107')as kode_nks,count(json_extract(uncompress(questionnaire), '$.id.P108'))as jmh_ruta,modified_time,created_time");
        $this->datatables2->select("concat('&#10148; KECAMATAN ',json_unquote(json_extract(uncompress(questionnaire), '$.BLOK_13.KEC_TEXT')))as kec,caseids,json_unquote(json_extract(uncompress(questionnaire), '$.id.P107'))as kode_nks,count(json_extract(uncompress(questionnaire), '$.id.P108'))as jmh_ruta");
        $this->datatables2->from('ssgi2022_dict2');
        //$this->datatables2->where("json_extract(uncompress(questionnaire), '$.id.P101')=13");
        //$this->datatables2->add_column("jmhbsbps",'$1','jmhbs(caseids)');
        // $this->datatables2->add_column("modified_time",'$1','convdatime(modified_time)');
        // $this->datatables2->add_column("created_time",'$1','convdatime(created_time)');
        $this->datatables2->where("json_extract(uncompress(questionnaire), '$.BLOK_13.KAB')=".$data."");
        $this->datatables2->group_by("json_extract(uncompress(questionnaire), '$.id.P107')");
        //add this line for join
        //$this->datatables2->join('table2', 'vis.field = table2.field');
        $this->datatables2->add_column('action', anchor(site_url('korwil2/nksview/$1'),'Lihat Daftra KK', array('class' => 'btn btn-default btn-sm')), 'substr(caseids, 11, 5)');
        return $this->datatables2->generate();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id,$di,$gp)
    {   $this->db->select($id);
        $this->db->where($di);
        $this->db->group_by($gp);
        return $this->db->get($this->table)->row();
        //$this->db->group_by($this->table);
        //return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
	$this->db->like("json_extract(uncompress(questionnaire), '$.id.P107')as kode_nks", $q);
	$this->db->or_like("json_unquote(json_extract(uncompress(questionnaire), '$.BLOK_13.KEC_TEXT')))as kec", $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
	$this->db->like("json_extract(uncompress(questionnaire), '$.id.P107')as kode_nks", $q);
	$this->db->or_like("json_unquote(json_extract(uncompress(questionnaire), '$.BLOK_13.KEC_TEXT')))as kec", $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // // insert data
    // function insert($data)
    // {
    //     $this->db->insert($this->table, $data);
    // }

    // // update data
    // function update($id, $data)
    // {
    //     $this->db->where($this->id, $id);
    //     $this->db->update($this->table, $data);
    // }

    // // delete data
    // function delete($id)
    // {
    //     $this->db->where($this->id, $id);
    //     $this->db->delete($this->table);
    // }

}

/* End of file Monitoring_model.php */
/* Location: ./application/models/Monitoring_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2023-02-10 10:37:36 */
/* http://harviacode.com */