<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Korwil_model extends CI_Model
{

    public $table = 'ssgi2022_dict';
    public $id = 'caseids';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }
    function get_by_id($id,$di,$gp)
    {   $this->db->select($id);
        $this->db->where($di);
        $this->db->group_by($gp);
        return $this->db->get($this->table)->row();
    }

}

/* End of file Monitoring_model.php */
/* Location: ./application/models/Monitoring_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2023-02-10 10:37:36 */
/* http://harviacode.com */